export const recycleMenu = [
  {
    id: 1,
    title: "Overview",
    navLink: "/recycle",
    type: "item",
    icon: "fas fa-tachometer-alt",
    parentId: null,
    parentName: null,
    displayOrder: 1,
    children: null,
  },
  {
    id: 2,
    title: "Application",
    navLink: "/recycle/application",
    type: "item",
    icon: "far fa-file",
    parentId: null,
    parentName: null,
    displayOrder: 1,
    children: null,
  },
  {
    id: 3,
    title: "University",
    navLink: "",
    type: "collapse",
    icon: "fas fa-university",
    parentId: null,
    parentName: null,
    displayOrder: 1,
    children: [
      {
        id: 0,
        title: "University",
        navLink: "/recycle/university",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 3,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Subjects",
        navLink: "/recycle/subjects",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 3,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
    ],
  },
  {
    id: 4,
    title: "User",
    navLink: "",
    type: "collapse",
    icon: "fas fa-user",
    parentId: null,
    parentName: null,
    displayOrder: 2,
    children: [
      {
        id: 0,
        title: "Student",
        navLink: "/recycle/student",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Consultant",
        navLink: "/recycle/consultant",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Affiliate",
        navLink: "/recycle/affiliate",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Companion",
        navLink: "/recycle/companion",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Admission Manager",
        navLink: "/recycle/admissionManager",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Admission Officer",
        navLink: "/recycle/admissionOfficer",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
      {
        id: 0,
        title: "Provider Admin",
        navLink: "/recycle/providerAdmin",
        type: "item",
        icon: "fas fa-angle-right",
        parentId: 4,
        parentName: null,
        displayOrder: 0,
        children: null,
      },
    ],
  },

  {
    id: 5,
    title: "Branch",
    navLink: "/recycle/branchManager",
    type: "item",
    icon: "fas fa-code-branch",
    parentId: null,
    parentName: null,
    displayOrder: 1,
    children: null,
  },
];
