export const tableIdList = {
    Staff_List : 1,
    Admission_Manager_List : 2,
    Admission_officer_List :3,
    Consultant_List : 4,
    Student_List : 5,
    University_List : 6,
    Intake_List : 7,
    Application_List : 8,
    Application_Transaction_List : 9,
    Account_Transaction_List : 10,
    Withdraw_Transaction_List : 11,
    Withdraw_request_List : 12,
    Provider_List : 13,
    Compliance_Officer_List : 14,
    Branch_List : 15,
    Admission_Manager_Application_List : 16,
    Consultant_Application_List : 17,
    Provider_Admin_Application_List : 18,
    Student_Application_List : 19,
    Campus_List : 20,
    University_Subject_List : 21,
    Associates_List : 22,
    Campus_Subject_List : 23,
}